#!/bin/bash

MY_PATH=`readlink -f $0`
cd `dirname $MY_PATH`

WORKER="tilesGen.pl"

if [ -a *.pid ] ; then
    echo "There is some pid file, investigate whether $WORKER is not running";
    exit 0;

fi

WORKDIR=`grep "WorkingDirectory" freemapdiskclient.conf | sed -e s/WorkingDirectory=//`

echo "Cleaning up $WORKDIR"
rm -rf "$WORKDIR"

echo "Starting $WORKER loop"
nohup nice -n 5 perl $WORKER loop >> output.log 2>&1 &
